// 特殊房间类型（Phase 11）
export const ROOM_TYPES = {
  TREASURE: {
    type: 'treasure',
    name: '宝藏室',
    rarity: 0.20,
    color: '#ffdd00',
    symbol: '$',
    description: '金光闪闪的密室，堆满了古老的金币...',
    loreCategory: 'world',
    effect: { gold: { min: 80, max: 200 } },
  },
  CURSE: {
    type: 'curse',
    name: '诅咒之间',
    rarity: 0.12,
    color: '#8800ff',
    symbol: '!',
    description: '黑暗能量从墙壁中渗出，空气中弥漫着不祥的气息...',
    loreCategory: 'dungeon',
    effect: { curse: true, hpCost: 0.25, rewardGold: 150 },
  },
  SHRINE: {
    type: 'shrine',
    name: '祝福祭坛',
    rarity: 0.18,
    color: '#ffffff',
    symbol: '+',
    description: '一座神圣的祭坛散发着温暖的光芒...',
    loreCategory: 'world',
    effect: { buff: { attack: 3, defense: 1 } },
  },
  MERCHANT: {
    type: 'merchant',
    name: '流浪商人',
    rarity: 0.08,
    color: '#44aaff',
    symbol: 'M',
    description: '一个披着斗篷的商人在阴影中向你招手...',
    loreCategory: 'items',
    effect: { merchant: true },
  },
  HEALING: {
    type: 'healing',
    name: '治愈之泉',
    rarity: 0.22,
    color: '#44ff88',
    symbol: 'H',
    description: '清澈的泉水从古老的喷泉中涌出...',
    loreCategory: 'dungeon',
    effect: { heal: { hpPct: 0.4, mpPct: 0.3 } },
  },
};
