// shared/config 统一导出
export { BOSS_TYPES } from './bosses.js';
export { MONSTER_TYPES, ELITE_MODIFIERS, ELITE_CHANCE, ELITE_DROP_BONUS, ELITE_GOLD_MULT, GOLD_DROPS } from './monsters.js';
export { EQUIPMENT_TYPES, ITEM_TYPES, MAX_STACK } from './equipment.js';
export { TOTAL_FLOORS, FLOORS, FLOOR_HP_SCALE, FLOOR_ATK_SCALE, FLOOR_MONSTER_COUNT, FLOOR_CLEAR_HP_PCT, FLOOR_CLEAR_MP_PCT, FLOOR_CLEAR_EXP_PER_FLOOR } from './floors.js';
export { ACHIEVEMENTS } from './achievements.js';
export { LORE_FRAGMENTS } from './lore.js';
export { PLAYER_HP, PLAYER_ATTACK_MIN, PLAYER_ATTACK_MAX, PLAYER_MP, PLAYER_STR, PLAYER_DEF, PLAYER_AGI, HEAL_AMOUNT, POST_BATTLE_HEAL, MP_RESTORE, EXP_BASE, LEVEL_UP_HP, LEVEL_UP_ATK_MIN, LEVEL_UP_ATK_MAX, LEVEL_UP_MP, LEVEL_UP_STR, LEVEL_UP_DEF, LEVEL_UP_AGI, INVENTORY_BASE_SLOTS, DROP_RATE } from './players.js';
export { BASE_CRIT, AGI_CRIT, CRIT_MULT } from './combat.js';
export { SKILLS } from './skills.js';
export { CAMP_HP_RESTORE, CAMP_MP_RESTORE, SHOP_ITEMS } from './camp.js';
export { GRID_SIZE, CELL_SIZE, OBSTACLE_COUNT, OBSTACLE_GEN_MAX_ATTEMPTS, OBSTACLE_STYLE, RENDER, COLOR, STAIRS_COLOR, STAIRS_LOCKED_COLOR, STAIRS_LABEL, STAIRS_LOCKED_LABEL, OBSTACLE_THEME, THEME_BG } from './render.js';
export { GAME_PHASE } from './phases.js';
export { TILE_DATA, TILE_SIZE, BIOME_PALETTES } from './tiles.js';
