// 粒子类型配置：每种粒子定义颜色、大小、速度、生命期、数量等
export const PARTICLE_TYPES = {
  crit: {
    colors: ['#ffaa00', '#ff6600', '#ffcc00', '#ffffff'],
    sizeMin: 2,
    sizeMax: 5,
    speedMin: 30,
    speedMax: 80,
    lifetimeMin: 0.3,
    lifetimeMax: 0.6,
    count: 8,
    shape: 'square',
    gravity: 20,
    spread: Math.PI * 2, // 全方向爆发
  },
  poison: {
    colors: ['#44ff44', '#88ff22', '#22cc22', '#66ff66'],
    sizeMin: 2,
    sizeMax: 4,
    speedMin: 10,
    speedMax: 25,
    lifetimeMin: 0.5,
    lifetimeMax: 1.0,
    count: 6,
    shape: 'circle',
    gravity: -5, // 向上飘
    spread: Math.PI * 0.5, // 窄角度向上
  },
  ice: {
    colors: ['#aaeeff', '#88ccff', '#ddddff', '#ffffff'],
    sizeMin: 2,
    sizeMax: 5,
    speedMin: 15,
    speedMax: 35,
    lifetimeMin: 0.4,
    lifetimeMax: 0.8,
    count: 7,
    shape: 'square',
    gravity: 10,
    spread: Math.PI * 1.5,
  },
  enrage: {
    colors: ['#ff2200', '#ff4400', '#ff6600', '#ff0000', '#ff8800'],
    sizeMin: 3,
    sizeMax: 7,
    speedMin: 40,
    speedMax: 100,
    lifetimeMin: 0.6,
    lifetimeMax: 1.2,
    count: 15,
    shape: 'square',
    gravity: 30,
    spread: Math.PI * 2,
  },
  loot: {
    colors: ['#ffdd00', '#ffaa00', '#ffcc44', '#ffffff'],
    sizeMin: 2,
    sizeMax: 4,
    speedMin: 20,
    speedMax: 60,
    lifetimeMin: 0.4,
    lifetimeMax: 0.7,
    count: 10,
    shape: 'square',
    gravity: -30, // 向上飘
    spread: Math.PI * 1.5,
  },
  heal: {
    colors: ['#44ff88', '#88ffaa', '#44ee66', '#ffffff'],
    sizeMin: 2,
    sizeMax: 4,
    speedMin: 10,
    speedMax: 30,
    lifetimeMin: 0.4,
    lifetimeMax: 0.8,
    count: 6,
    shape: 'circle',
    gravity: -15,
    spread: Math.PI * 0.6,
  },
};
